language: cpp

compiler:
  - clang
# - gcc

# use travis-ci docker based infrastructure
sudo: false

cache:
  directories:
    - $HOME/.ccache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - autoconf
    - ccache
    - clang-3.4
    - cmake
    - g++-4.8
    - libgmp3-dev
    - liblzma-dev
    - libncurses5-dev
    - libreadline-dev
    - libsqlite3-dev
    - libtool
    - ninja-build
    - python-dev
    - texlive-extra-utils

before_install:
  - wget http://www.cmake.org/files/v3.2/cmake-3.2.1-Linux-x86_64.tar.gz
  - tar zxf cmake-3.2.1-Linux-x86_64.tar.gz
  - export PATH=`pwd`/cmake-3.2.1-Linux-x86_64/bin:$PATH
  - if [ "$CXX" = "g++" ]; then export CC="gcc-4.8" CXX="g++-4.8"; fi

install:
  - git clone git://github.com/llvm-mirror/llvm.git ~/pyston_deps/llvm-trunk
  - git clone git://github.com/llvm-mirror/clang.git ~/pyston_deps/llvm-trunk/tools/clang
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - mkdir ~/pyston-build && cd ~/pyston-build
  - make -C $TRAVIS_BUILD_DIR llvm_up
  - cmake -GNinja $TRAVIS_BUILD_DIR
  - ninja libunwind ext_cpython

script:
  - ccache -z
  - ninja -j4 check-pyston
  - ccache -s

os:
  - linux
# - osx

notifications:
  irc:
    channels:
      - "chat.freenode.net#pyston"
    on_success: [change]

  webhooks:
    urls:
      - https://webhooks.gitter.im/e/7256425a36658faa8b9b
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
